"""Add risk_score risk_reasoning clause_subtype to clauses

Revision ID: ce01b6abad24
Revises: ee476f61c318
Create Date: 2025-12-31 03:12:58.340440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce01b6abad24'
down_revision = 'ee476f61c318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clauses', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('clauses', sa.Column('risk_reasoning', sa.Text(), nullable=True))
    op.add_column('clauses', sa.Column('clause_subtype', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clauses', 'clause_subtype')
    op.drop_column('clauses', 'risk_reasoning')
    op.drop_column('clauses', 'risk_score')
    # ### end Alembic commands ###

